name: flame_raycast_fps
description: FPS game using custom raycasting renderer on Flame

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

     # FLAME
  flame: ^1.8.1
  flame_bloc: ^1.10.0
  flame_audio: ^2.0.4
  flame_forge2d: ^0.14.1
  flame_lint: ^1.0.0
  flame_svg: ^1.8.0
  flame_tiled: ^1.12.0

    #OTHER
  flutter_bloc: ^8.1.3
  freezed: ^2.3.2
  get_it: ^7.2.0
  injectable: ^2.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  canvas_test:
  flame_test: ^1.9.2  


  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets/

  uses-material-design: true


